### ISSUE TITLE
Suggestion for Improving the Gem Purchase Process

### ISSUE THREAD

**Issue by SonYoungsung** [tokamak-network/gem-marketplace#27]
It seems that users need to submit transactions twice to obtain a single gem. However, this might be confusing as the sign pop-up appears without any prior notice or explanation. Adding a clear prompt or indication before each step could improve the overall user experience.

![chrome_WJVVmlqjFs](https://github.com/user-attachments/assets/cd3be6d3-4c42-445f-a971-e472cc7254ed)

**Comment by Mehd1b** [comment]
@SonYoungsung this is a temporary process. Since DRB nodes are not running yet, we have to fill some functions manually and that's why users must sign 2 transactions. This will be adjusted once DRB product is launched
