### ISSUE TITLE
Implement a maximum limit 2 for decimal places in TON and WSTON balances, you can use the Math.Round()

### ISSUE THREAD

**Issue by parth-tokamak** [tokamak-network/gem-marketplace#6]
<img width="339" alt="image" src="https://github.com/user-attachments/assets/23235037-1998-4391-a0f0-50892b6822da">

**Comment by jusdy** [comment]
@parth-tokamak fixed

**Comment by parth-tokamak** [comment]
@jusdy 
<img width="356" alt="image" src="https://github.com/user-attachments/assets/cae10f5b-0262-43cb-bc15-39b3c906a80b">
<img width="368" alt="image" src="https://github.com/user-attachments/assets/61355dce-2d6a-41ac-92d6-0234ffe7ae9a">

We need to show 15.97

```
Example:- 
const number = 15.966
const rounded = Math.round(number * 100) / 100
console.log(rounded) // Outputs: 15.97
```
